language: python
python: 2.7
env:
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pep8
install:
    - pip install tox
    - pip install coveralls
script:
    - tox
after_success:
    - coveralls
