language: python
python: 2.7
env:
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
install:
    - python setup.py -q install
    - pip install virtualenv
    - pip install coveralls
script:
    - python setup.py test
after_success:
    - coveralls
